name: cuzdanim_app
description: "gelir-gider girilen, bakiye gÃ¶steren takip uyg"

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.6.1


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite: ^2.4.2
  sqflite_common_ffi: ^2.3.5
  path: ^1.9.1
  path_provider: ^2.1.5
  fl_chart: ^0.70.2
  shared_preferences: ^2.2.2
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/images/sonArkaplan.png
    - assets/images/halbuki.jpg
    - assets/images/profil.jpg
    - assets/images/PS.png
    - assets/images/nomoney.jpg